version: "3"

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: fitcoDB
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
